feat: deployment script using starkli
keep-starknet-strange/satoru pull request #371
Opened 2023-09-10 23:57 UTC by sparqet

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

- deployment script for role_store
-
-

## Does this introduce a breaking change?

 No

## Other information

2023-09-10 23:59 UTC, Sk8erboi84 requested changes

2023-09-10 23:59 UTC, Sk8erboi84 commented on scripts/deploy_role_store_contract.sh
> +command_output=$(starkli declare ../target/dev/satoru_RoleStore.sierra.json)
Explain each line

2023-09-10 23:59 UTC, Sk8erboi84 commented on scripts/deploy_role_store_contract.sh
> +from_char=":"
Explain each line

2023-09-10 23:59 UTC, Sk8erboi84 commented on scripts/deploy_role_store_contract.sh
> +class_hash=$(echo "$command_output" | sed 's/.*'$from_char'//')
Explain each line

2023-09-10 23:59 UTC, Sk8erboi84 commented on scripts/deploy_role_store_contract.sh
> +starkli deploy $class_hash
Explain each line

2023-09-11 00:05 UTC, zarboq approved these changes

2023-09-11 00:05 UTC, Sk8erboi84 commented
Please change the issue and remove sncast and add starkli

2023-09-11 00:06 UTC, Sk8erboi84 approved these changes

2023-09-11 00:09 UTC, merged