Feature: implement bank/bank.cairo, token/token_utils.cairo and write tests
keep-starknet-strange/satoru pull request #372
Opened 2023-09-11 00:02 UTC by Darlington02

Implemented the functions in bank/bank.cairo, implemented the token_utils helper functions and wrote tests for the bank/bank.cairo contract.

# Pull Request type
- Feature

## Does this introduce a breaking change?

No

2023-09-11 00:05 UTC, Sk8erboi84 approved these changes

2023-09-11 14:54 UTC, Sk8erboi84 commented on src/token/token_utils.cairo
> +        // transfer tokens to receiver and return if it suceeeds
Add a TODO for the gas limit please

2023-09-11 14:54 UTC, Sk8erboi84 commented on src/token/token_utils.cairo
> +        }
Dont forget to validate_receiver

2023-09-11 14:54 UTC, Sk8erboi84 commented on src/token/token_utils.cairo
> +        assert(success1 == true, 'token_transfer_failed');
add : "token_transfer_failed" in the error file and call it

2023-09-11 14:55 UTC, Sk8erboi84 commented
In the bank file you need to inherit role module (like in swap_handler)

2023-09-11 22:16 UTC, Sk8erboi84 requested changes
Please fix the comments so we can merge it

2023-09-11 22:26 UTC, Darlington02 commented
> In the bank file you need to inherit role module (like in swap_handler)

Sure I could, but I'm not sure I can find the use case for it in the Solidity Implementation

> Please fix the comments so we can merge it

yeap, on it...will make a push in few minutes:)

2023-09-12 22:24 UTC, Sk8erboi84 approved these changes

2023-09-12 22:36 UTC, merged