Feat: implemented withdrawal_utils functions
keep-starknet-strange/satoru pull request #376
Opened 2023-09-12 06:53 UTC by ametel01

# Pull Request type

- Feature

Resolves: #359 

## Other information
Implemented using IStrictBank interface instead of the IWithdrawalVault as found in the Solidity version. Please confirm if this needs to be updated.

2023-09-13 17:18 UTC, sparqet requested changes

2023-09-13 17:18 UTC, sparqet commented on src/withdrawal/withdrawal_utils.cairo
> +    let mut cache: SwapCache = Default::default();
Declare the struct with angle brackets

2023-09-13 22:02 UTC, ametel01 commented on src/withdrawal/withdrawal_utils.cairo
> +    let mut withdrawal: Withdrawal = Default::default();
done

2023-09-13 22:03 UTC, ametel01 commented on src/withdrawal/withdrawal_utils.cairo
> +    let mut cache: SwapCache = Default::default();
implemented

2023-09-13 23:13 UTC, ametel01 commented on src/withdrawal/withdrawal_utils.cairo
> +    let mut event_data: EventLogData = Default::default();
Thanks for your review. I've eliminated all references to EventLogData and have only left the event emitter call in place. Could you clarify the point you were making earlier?

2023-09-13 23:13 UTC, ametel01 commented on src/event/event_utils.cairo
>  struct EventLogData {
Thanks for your review. I've eliminated all references to EventLogData and have only left the event emitter call in place. Could you clarify the point you were making earlier?

2023-09-13 23:13 UTC, ametel01 commented on src/event/event_utils.cairo
> +struct AddressItems {
removed

2023-09-13 23:13 UTC, ametel01 commented on src/event/event_utils.cairo
> +    fn set_item(ref self: T, key: felt252, value: A);
removed

2023-09-13 23:13 UTC, ametel01 commented on src/withdrawal/withdrawal_utils.cairo
> +    event_data.address_items.set_item('output_token', result.output_token);
Thanks for your review. I've eliminated all references to EventLogData and have only left the event emitter call in place. Could you clarify the point you were making earlier?

2023-09-15 21:21 UTC, sparqet commented on src/withdrawal/withdrawal_utils.cairo
> +    event_data.address_items.set_item('output_token', result.output_token);
In our implementation, each event is emitted by a specific emitter

2023-09-15 21:22 UTC, sparqet approved these changes
LGTM

2023-09-15 23:35 UTC, merged