Feat/ald utils
keep-starknet-strange/satoru pull request #378
Opened 2023-09-12 13:57 UTC by tevrat-aksoy

## What is the current behavior?

Resolves: #250 
Tests not completed because of the missing libraries and mock_call doesnt work with inner calls
## Other information

2023-09-13 13:20 UTC, zarboq requested changes

2023-09-13 15:17 UTC, tevrat-aksoy commented on src/event/event_emitter.cairo
> +        fn emit_event_log1(
I updated the event .
```
fn emit_adl_state_updated(
    event_emitter: IEventEmitterDispatcher,
    market: ContractAddress,
    is_long: bool,
    pnl_to_pool_factor: i128,
    max_pnl_factor: u128,
    should_enable_adl: bool
) {
    event_emitter
        .emit_adl_state_updated(
            market, is_long, pnl_to_pool_factor.into(), max_pnl_factor, should_enable_adl,
        );
}
```
https://github.com/tevrat-aksoy/satoru/blob/a47ec555abbdceaf8712a4d01f890bb406152e76/src/adl/adl_utils.cairo#L302C1-L305C11

2023-09-14 13:33 UTC, zarboq approved these changes

2023-09-14 13:33 UTC, sparqet approved these changes
LGTM

2023-09-14 13:33 UTC, merged