test: add a test for `exchange_utils`
keep-starknet-strange/satoru pull request #383
Opened 2023-09-13 12:19 UTC by delaaxe

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

## What is the current behavior?

Resolves: #281

## Other information

Requires `forge==0.6.0` which should be released imminently

2023-09-24 15:05 UTC, delaaxe commented
blocked by this foundry issue: https://github.com/foundry-rs/starknet-foundry/issues/659

2023-10-18 22:30 UTC, delaaxe commented
@zarboq @sparqet you can review

2023-10-19 08:49 UTC, zarboq requested changes
Test naming issue, else everything looks good :fire:

2023-10-19 08:49 UTC, zarboq commented on tests/exchange/test_exchange_utils.cairo
> +fn test_exchange_utils() {
rename test to follow our naming conventions

ex: `given_division_by_0_when_roundup_magnitude_division_then_fails`

2023-10-19 17:17 UTC, zarboq approved these changes

2023-10-19 17:17 UTC, merged