Feat/position pricing utils
keep-starknet-strange/satoru pull request #412
Opened 2023-09-17 17:32 UTC by sparqet

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Testing

## What is the new behavior?

- implemented position pricing utils functions

## Does this introduce a breaking change?

No

2023-09-22 13:34 UTC, zarboq commented on src/pricing/position_pricing_utils.cairo
> +fn _get_price_impact_usd(
don't start with _

2023-09-22 13:34 UTC, zarboq reviewed
Some functions are missing documentation

2023-09-25 12:21 UTC, zarboq requested changes
Great PR overall :rocket:

Added some minor fix request

2023-09-25 18:45 UTC, sparqet commented on src/pricing/position_pricing_utils.cairo
> +    let is_same_side_rebalance_first = open_interest_params
I tried to, but doesn't work

2023-09-25 21:08 UTC, Sk8erboi84 approved these changes

2023-09-25 21:41 UTC, zarboq approved these changes

2023-09-25 21:41 UTC, merged