Jordyro1/oracle module library
keep-starknet-strange/satoru pull request #413
Opened 2023-09-18 09:08 UTC by JordyRo1

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
X Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #297 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

 No

## Other information

2023-09-18 10:27 UTC, zarboq requested changes
Minor change then good to go !

2023-09-18 10:27 UTC, zarboq commented on src/oracle/oracle_modules.cairo
> +use starknet::ContractAddress;
Add this under `// Core lib imports`

2023-09-18 10:27 UTC, zarboq commented
Fix checks also please

2023-09-18 12:50 UTC, zarboq commented on src/oracle/oracle_modules.cairo
> +use satoru::price::price::Price;
I meant only starknet::* imports under `Core lib`

satoru::* imports always under `Local imports`

2023-09-18 12:52 UTC, JordyRo1 commented on src/oracle/oracle_modules.cairo
> +use satoru::price::price::Price;
ooh I see

2023-09-18 13:09 UTC, zarboq approved these changes

2023-09-18 13:32 UTC, JordyRo1 commented
There are still an issue with the test/check. Previously, since there was an empty ```with_oracle_prices_before```, the test expected to fail at invalid_withdraw_key. Now that there is the function ```oracle.set_prices``` it seems to fails at the function ```validate_role``` of the function ```only_controller``` called in ```set_prices```. Is that a normal behaviour or should I dig to find the issue ?

2023-09-18 14:01 UTC, zarboq commented
I think you should grant the corresponding role in tests

2023-09-18 17:39 UTC, JordyRo1 commented
I granted the role::CONTROLLER to the order_keeper (he already had role::ORDER_KEEPER). The issue is that function ```set_prices``` still returns the same error. The issue is that the function ```get_caller_address``` returns an address different from the defined ```order_keeper``` defined in the example.

2023-09-19 08:18 UTC, JordyRo1 commented
Everything should be good !

2023-09-19 12:00 UTC, merged