Feat/referral utils
keep-starknet-strange/satoru pull request #418
Opened 2023-09-18 14:24 UTC by Sk8erboi84

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

## Other information

2023-09-18 17:02 UTC, zarboq requested changes

2023-09-18 17:02 UTC, zarboq commented on src/referral/referral_utils.cairo
>      // TODO
remove todo

2023-09-18 17:02 UTC, zarboq commented on src/referral/referral_utils.cairo
> +
```
MarketToken(payable(market)).transferOut(
            token,
            receiver,
            rewardAmount
        );
```

This is missing

2023-09-19 20:31 UTC, closed without merging

2023-09-19 20:32 UTC, Sk8erboi84 commented
Will do a PR on another branch/P{R