implemented external functions
keep-starknet-strange/satoru pull request #450
Opened 2023-09-25 23:22 UTC by sparqet

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Testing

## What is the new behavior?

- Implemented deposit_handler contract

## Does this introduce a breaking change?

No

2023-09-25 23:41 UTC, Sk8erboi84 requested changes
Create the initialize function and call it in the constructor and move everything from the constructor to the initialize function

2023-09-25 23:43 UTC, Sk8erboi84 commented
Document the function

2023-09-27 22:55 UTC, zarboq requested changes

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
>          fn create_deposit(
missing role checks, contract should import IRoleModule and RoleModule and call it's initializer, role_store should be removed from this contract storage.

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
>          fn create_deposit(
Also missing global reentrancy

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
> +        fn cancel_deposit(ref self: ContractState, key: felt252) {
same

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
> +        fn execute_deposit(ref self: ContractState, key: felt252, oracle_params: SetPricesParams) {
same

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
> +        fn execute_deposit(ref self: ContractState, key: felt252, oracle_params: SetPricesParams) {
also oracle price

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
> +/// TODO not needed
```suggestion
/// TODO no try catch, we need to find alternative
```

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
>          fn simulate_execute_deposit(
same

2023-09-27 22:55 UTC, zarboq commented on src/exchange/deposit_handler.cairo
>          fn execute_deposit_keeper(
same

2023-09-28 14:14 UTC, zarboq reviewed
small fix in execute_deposit_keeper

2023-09-28 14:25 UTC, zarboq approved these changes

2023-09-28 14:33 UTC, zarboq approved these changes

2023-09-28 14:39 UTC, Sk8erboi84 approved these changes

2023-09-28 14:39 UTC, merged