Feat: Implement the function in the market_utils library. #1, part 1
keep-starknet-strange/satoru pull request #459
Opened 2023-09-27 20:01 UTC by delaaxe

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Resolves: #NA

2023-09-28 13:48 UTC, zarboq requested changes
Implemented functions are clean but I think some are missing. This is the one I noted from the GMX file:

```
getNetPnl
getCappedPnl
getPnl (2nd implem with index_token_price as u128)
claimFundingFees
claimCollateral
applyDeltaToPoolAmount
getAdjustedPositionImpactFactor
getAdjustedPositionImpactFactors
getCappedPositionImpactUsd
applyDeltaToOpenInterestInTokens
applyDeltaToCollateralSum
updateFundingState
getNextFundingAmountPerSize
```

2023-10-01 17:42 UTC, delaaxe commented on src/market/market_utils.cairo
> +        MarketError::UNABLE_TO_GET_CACHED_TOKEN_PRICE(token)
done

2023-10-02 00:31 UTC, sparqet approved these changes

2023-10-02 08:32 UTC, zarboq approved these changes

2023-10-02 12:54 UTC, merged