Feat: increase_position_utils library
keep-starknet-strange/satoru pull request #510
Opened 2023-10-10 15:41 UTC by sparqet

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

## What is the current behavior?

Resolves: #NA

## What is the new behavior?

- implemented increase_position_utils library

## Does this introduce a breaking change?

No

2023-10-12 13:39 UTC, zarboq requested changes

2023-10-12 13:39 UTC, zarboq commented on src/position/increase_position_utils.cairo
> +    (price_impact_usd, price_impact_amount, size_delta_in_tokens_unsigned, execution_price)
```suggestion
    (price_impact_usd, price_impact_amount, to_unsigned(size_delta_in_tokens), execution_price)
```

2023-10-12 20:37 UTC, Sk8erboi84 commented
@sparqet Please fix your tests

2023-10-15 00:17 UTC, zarboq approved these changes

2023-10-15 00:21 UTC, merged