Improve tests of liquidation_handler contract
keep-starknet-strange/satoru pull request #589
Opened 2023-11-14 08:21 UTC by tevrat-aksoy

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #NA

#479

2023-11-22 17:26 UTC, zarboq requested changes
Small fixes then good to go

2023-11-22 17:26 UTC, zarboq commented on tests/exchange/test_liquidation_handler.cairo
> +use satoru::oracle::{interfaces::account::{IAccount, IAccountDispatcher, IAccountDispatcherTrait}};
merge imports that have the same path

2023-11-22 17:26 UTC, zarboq commented on src/exchange/liquidation_handler.cairo
>      use satoru::exchange::base_order_handler::BaseOrderHandler::{
You can put this under // Local imports

2023-11-22 18:58 UTC, tevrat-aksoy commented on src/exchange/base_order_handler.cairo
> +    fn only_liquidation_keeper(self: @TContractState);
fixed here
https://github.com/tevrat-aksoy/satoru/commit/c5354902dd17997a0ff6b24971a6204b4e1c07c0

2023-11-23 15:42 UTC, zarboq approved these changes

2023-11-23 15:43 UTC, zarboq commented
LGTM :rocket:

2023-11-23 15:43 UTC, merged