feat: full deployment script in ts
keep-starknet-strange/satoru pull request #613
Opened 2024-02-12 17:40 UTC by zarboq

# Pull Request type

- Feature

## What is the new behavior?

- Full deployment script in TS, tested with Katana local network. 
- Added admin argument in RoleStore constructor because when deployed through UDC, UDC would get ownership

2024-02-12 19:13 UTC, Sk8erboi84 requested changes

2024-02-12 19:14 UTC, Sk8erboi84 commented
I dont know if its better but create a function to deploy the contract instead of doing the same thing each time you want to deploy

2024-02-13 10:25 UTC, zarboq commented
I think since I'll need to prepare the arguments before calling the function it will be the same as now

2024-02-13 19:51 UTC, Sk8erboi84 approved these changes

2024-02-13 19:53 UTC, merged